sdk: "/Users/alexb/.rvm/gems/ruby-1.9.3-p547/gems/rhodes-5.0.3.beta.12"
#sdkversion: 5.0.0
name: store-push-demo
version: 1.0
vendor: rhomobile
build: debug
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator7.0
  provisionprofile:
  codesignidentity: iPhone Developer
  entitlements: ""
  BundleIdentifier: com.rhomobile.store-manager
  BundleURLScheme: store-manager
wp8:
  productid: 'df63d480-0a13-0132-232a-60f847211b08'
android:
  manifest_template: 'AndroidManifest.erb'
  version: 4.4.2

wm:
  #sdk: "MC3000c50b (ARMV4I)"
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"

#extensions: ["rhoconnect-client"]
extensions: ["rhoconnect-client", "rhoconnect-push"]
